trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: AzureResourceManagerTemplateDeployment
  inputs:
    deploymentScope: 'Resource Group'
    subscriptionId: '7623bf57-5a1c-4dc6-8470-0f27049d9210'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'demogroup'
    location: 'West US'
    templateLocation: 'asqw.json'
    csmFileLink: 'asqw.json'
    csmParametersFileLink: ''
    deploymentMode: 'Incremental'
    deploymentName: 'deploy1'
